train:
    _target_: getsits.engine.data_preprocessor.Preprocessor
    preprocessor_cfg:
        - _target_: getsits.engine.data_preprocessor.ResizeToEncoder
        - _target_: getsits.engine.data_preprocessor.BandFilter
        - _target_: getsits.engine.data_preprocessor.BandPadding

val:
    _target_: getsits.engine.data_preprocessor.Preprocessor
    preprocessor_cfg:
        - _target_: getsits.engine.data_preprocessor.ResizeToEncoder
        - _target_: getsits.engine.data_preprocessor.BandFilter
        - _target_: getsits.engine.data_preprocessor.BandPadding

test:
    _target_: getsits.engine.data_preprocessor.Preprocessor
    preprocessor_cfg:
        - _target_: getsits.engine.data_preprocessor.ResizeToEncoder
        - _target_: getsits.engine.data_preprocessor.BandFilter
        - _target_: getsits.engine.data_preprocessor.BandPadding
