train: true
pretrain: true
work_dir: "./results"
seed: 242
use_wandb: false
wandb_run_id: null
wandb_project: ""

# TRAINING
num_workers: 4
batch_size: 4
lars: false
projection_dim: 256

test_num_workers: 4
test_batch_size: 4

# EXPERIMENT
finetune: true
from_scratch: true
ckpt_dir: null
limited_label_train: 1
limited_label_val: 1
limited_label_strategy: stratified  # Options: stratified, oversampled, random
stratification_bins: 3 #  number of bins for stratified sampling, only for stratified
data_replicate: 1


defaults:
  - task: pretraining
  - dataset: ???
  - encoder: ???
  - decoder: seg_upernet_mt_ltae
  - preprocessing: pretrain_default
  - criterion: ???
  - lr_scheduler: cosine_annealing
  - optimizer: adamw
  - _self_ 
