_target_: getsits.encoders.olmoearth.OlmoEarth
encoder_weights: ./pretrained_models/weights.pth
download_url: https://huggingface.co/allenai/OlmoEarth-v1-Tiny/resolve/main/weights.pth

embed_dim: 192
input_size: 224
patch_size: 16
depth: 12
num_heads: 3
mlp_ratio: 4
positional_encoding: "normal"

input_bands: 
  optical:
    - B1
    - B2
    - B3
    - B4
    - B5
    - B6
    - B7
    - B8
    - B8A
    - B9
    - B11
    - B12

  
output_layers:
  - 3
  - 5
  - 7
  - 11

output_dim: 192