_target_: getsits.encoders.vit.VIT_Encoder
model_name: "ViT-Small"
encoder_weights: ./pretrained_models/vit_s_lesits.pth
download_url: null

embed_dim: 384
input_size: 224
patch_size: 16
depth: 12
num_heads: 6
mlp_ratio: 4
positional_encoding: "normal"

input_bands: 
  optical:
    - B1
    - B2
    - B3
    - B4
    - B5
    - B6
    - B7
    - B8
    - B8A
    - B9
    - B11
    - B12

  
output_layers:
  - 3
  - 5
  - 7
  - 11

output_dim: 384
